### ISSUE TITLE
C & D

### ISSUE THREAD

**Issue by ghost** [thlorenz/readline-vim#1]
"D" in normal mode should delete everything ahead of the cursor.
"C" in normal mode should delete everything ahead of the cursor and put you into insert mode.
Right now "D" and "dd" & "C" and "cc" do the same things.

**Comment by thlorenz** [comment]
good catch, I will look into this once I get the time.
I accept well tested pull requests btw ;)

**Comment by ghost** [comment]
I'm currently just learning node. I wanted to have vim keybindings in the
node repl and I stumbled on your project. Once I learn a bit more I'd be
more than happy to pull and fix! One question though: `repl.start` starts
and returns a REPLServer instance, on which you access a .rli property. How
did you know about the properties of that object? I can't find it anywhere
in node's documentation. Is there another place to look to find out these
kinds of things or do you usually just learn by reading the source?
Thanks!

**Comment by thlorenz** [comment]
No worries, although really getting into something and trying to understand it to the point where you can contribute is a good way to learn as well.
On another note, you might like [replpad](http://thlorenz.github.io/replpad/). It adds vim bindings to the repl among lots of other features.
