### ISSUE TITLE
short delay when switching to normal mode

### ISSUE THREAD

**Issue by timkuijsten** [thlorenz/readline-vim#5]
when pressing escape in insert mode it takes a short delay (maybe 200 msec) before you actually enter normal mode. because this interferes with fast navigation I was wondering if this delay can be disabled?

**Comment by thlorenz** [comment]
Interesting I never noticed that - I'm not aware that I added a delay anywhere, could you refer me to the part in the code please that adds this delay.
If so I believe we can disable this.

**Comment by timkuijsten** [comment]
I've been looking in the code but can not really find the source of the problem.

If I run `npm run demo` there is no delay when pressing escape. But if I copy the repl example into a file test.js that I run with node, the delay is there again.

**Comment by timkuijsten** [comment]
running this with node triggers the delay on my machine https://gist.github.com/timkuijsten/6977027

**Comment by raoofha** [comment]
I think the current problem is [here](https://github.com/nodejs/node/blob/v9.10.1/lib/readline.js#L60) and the relevent [issue](https://github.com/nodejs/node/issues/7379)
if somebody want to solve it, it would be awsome

**Comment by timkuijsten** [comment]
I've rewritten [node-mongovi](https://github.com/timkuijsten/node-mongovi) into a [pure C variant](https://github.com/timkuijsten/mongovi) using libedit so I no longer require readline-vim or nodejs.

**Comment by nkabbara** [comment]
Hey all, is there a workaround to remove the esc delay?

I start my repl by running a script (I load custom objects into my global env).

Thanks!

**Comment by raoofha** [comment]
you can use `escapeCodeTimeout` option
```javascript
const rlv = require('readline-vim')
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  escapeCodeTimeout: 50,
});

rl.question('What do you think of Node.js? ', (answer) => {
  // TODO: Log the answer in a database
  console.log(`Thank you for your valuable feedback: ${answer}`);
  rl.close();
});

rlv(rl);
```

**Comment by nkabbara** [comment]
Thanks @raoofha!

How would one integrate that interface into repl? When I do something like below, it's typing in doubles. So if I type 'k; in the console, it would type 'kk'. 

I can't find an option in node repl docs on passing it a customer interface.

```
let repl = require('repl');
let path = require('path')
let os = require('os')
let rlv = require('readline-vim')
const readline = require('readline');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  escapeCodeTimeout: 50
});

let replServer = repl.start({
  prompt: 'kwrr > ',
});

replServer.setupHistory(path.join(os.homedir(), '.node_repl_history'), (e) => null)

rlv(rl)
var vim = rlv(replServer)
```

**Comment by raoofha** [comment]
it's been a long time since I used this library. the problem is in [here](https://github.com/nodejs/node/blob/5a042a6b1a9763be010c4614436b114f0d514561/lib/repl.js#L584) `escapeCodeTimeout` never passed to `readline` interface function. it you make a pull request to node and fix it you should be able to use it like this

```javascript
let repl = require('repl');
let path = require('path')
let os = require('os')
let rlv = require('readline-vim')

let replServer = repl.start({
  prompt: 'kwrr > ',
  escapeCodeTimeout: 50,
});

replServer.setupHistory(path.join(os.homedir(), '.node_repl_history'), (e) => null)

var vim = rlv(replServer)
```

**Comment by nkabbara** [comment]
Thanks @raoofha. I took a different route using rlwrap.

In case anyone is wondering about this in the future something like below might work for you:

`NODE_NO_READLINE=1 rlwrap -t dumb --always-readline node <your custom repl script name>`
